name: flutter_telegram_web_app
description: Build a Telegram Web App using Flutter Web
version: 0.0.1
homepage: https://github.com/rohitsangwan01/flutter_telegram_web_app
repository: https://github.com/rohitsangwan01/flutter_telegram_web_app
issue_tracker: https://github.com/rohitsangwan01/flutter_telegram_web_app/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
